/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "chebyshev.h"
#include <sys/types.h>

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

result_data *
solve_system_1(matrix_data *argp, CLIENT *clnt)
{
	static result_data clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SOLVE_SYSTEM,
		(xdrproc_t) xdr_matrix_data, (caddr_t) argp,
		(xdrproc_t) xdr_result_data, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
