/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "chebyshev.h"
#include <sys/types.h>

bool_t
xdr_result_data (XDR *xdrs, result_data *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->solution.solution_val, (u_int *) &objp->solution.solution_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->computation_time))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_matrix_data (XDR *xdrs, matrix_data *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->matrix.matrix_val, (u_int *) &objp->matrix.matrix_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->vector.vector_val, (u_int *) &objp->vector.vector_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}
