/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "czebyszew.h"

bool_t
xdr_DynamicArray (XDR *xdrs, DynamicArray objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 25,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_LinearSystem (XDR *xdrs, LinearSystem *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->matrix, 25,
		sizeof (DynamicArray), (xdrproc_t) xdr_DynamicArray))
		 return FALSE;
	 if (!xdr_DynamicArray (xdrs, objp->vector))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->errorTolerance))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->maxIterations))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SolverResult (XDR *xdrs, SolverResult *objp)
{
	register int32_t *buf;

	 if (!xdr_DynamicArray (xdrs, objp->solutionVector))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->iterationsPerformed))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}
